import Config

# Configure your database
config :universal_enterprise_platform, UniversalEnterprisePlatform.Infrastructure.Repos.Repo,
  username: System.get_env("DB_USER") || "postgres",
  password: System.get_env("DB_PASSWORD") || "postgres",
  hostname: "localhost",
  database: "universal_enterprise_platform_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  log_level: :debug

config :universal_enterprise_platform,
       UniversalEnterprisePlatform.Infrastructure.Repos.TimescaleRepo,
       username: System.get_env("DB_USER") || "postgres",
       password: System.get_env("DB_PASSWORD") || "postgres",
       hostname: "localhost",
       database: "universal_enterprise_platform_ts_dev",
       pool_size: 5

config :universal_enterprise_platform,
  starrocks_enabled: false

config :universal_enterprise_platform, :tigerbeetle_enabled, true

config :universal_enterprise_platform, :tigerbeetle,
  cluster_id: 0,
  addresses: ["127.0.0.1:3001"]

config :universal_enterprise_platform, :spicedb,
  endpoint: "127.0.0.1:50051",
  preshared_key: "secret123"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :universal_enterprise_platform, UniversalEnterprisePlatformWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "lzep+r29KvJfPyg+iQJErrmUBHTD/fegI9RMkuQIc6I62/qn+YCT6wSY+zVb9A5y",
  watchers: [
    esbuild:
      {Esbuild, :install_and_run,
       [:universal_enterprise_platform, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:universal_enterprise_platform, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :universal_enterprise_platform, UniversalEnterprisePlatformWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/universal_enterprise_platform_web/router\.ex$"E,
      ~r"lib/universal_enterprise_platform_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

config :universal_enterprise_platform, :meilisearch,
  url: System.get_env("MEILI_URL") || "http://127.0.0.1:7700",
  api_key: System.get_env("MEILI_API_KEY")

# Enable dev routes for dashboard and mailbox
config :universal_enterprise_platform, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
